#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  block compile bundler
  ln -nfs "$shome/vendor/bundle/bin/tugboat" "$shome/bin/"
}

bootstrap
